### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by mappu** [m-barthelemy/BackO#1]
Hi! This is a fascinating project and it looks like a lot of work has gone into it.

Under what terms is it available?
- You don't care what happens now (WTFPL)
- Free for either open or closed-source use/modification, with attribution (BSD/MIT/ISC)
- Any use/modification must remain open source (GPL)

**Comment by m-barthelemy** [comment]
Hi, Thanks for your interest in this project.
I had never thought about the exact license to use. Let's say BSD.

That being said, I doubt you'll get anywhere with this project. It was mostly a big C# self-learning exercise for me, and even if some parts probably works well, other haven't been implemented.

Even more important, it has been unmaintained for years, and, being a way for me to learn and practise, it probably violates many coding style, rules and best practices.

I'd be happy to help if you have more questions.
